# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a6209b20fcd7e64eadc6d5c7665e65f687abcf828001764cc0b73ba723c92ad9e88172edc21e250fc916f42a9475d3046fe402975f49a25d4342d3f19a6a6e1

test:
  secret_key_base: 29ede492cac8a5261fc474972e93dfbe7528c1f8ea2faf00c6992ddb9c7303e82e13408ffea6a965add94a254bf23d509131a42ad12d48b2ba2121df62412d9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
